"""
Report rendering.

Builds a human-readable markdown report and a machine-readable JSON
report from the collected metrics, optimization findings and pending
updates. The JSON payload is shaped so it can be served as a shields.io
endpoint badge payload for "GitHub vision" dashboards.
"""

from __future__ import annotations

import json
from typing import Dict, List, Optional

from .collectors import current_time, format_uptime
from .optimizations import Finding, grade
from .updates import PendingUpdate

SEVERITY_WEIGHT = {"info": 0, "warning": 1, "critical": 2}


def build_context(metrics: Dict) -> Dict:
    return {
        "hostname": metrics.get("hostname", "unknown"),
        "platform": f"{metrics.get('platform', 'unknown')} {metrics.get('release', '')}".strip(),
        "arch": metrics.get("arch"),
        "python": metrics.get("python_version"),
        "uptime": format_uptime(metrics.get("uptime_days")),
        "cores": metrics.get("cores"),
        "scan_time": current_time(),
    }


def render_markdown(
    metrics: Dict,
    findings: List[Finding],
    updates: List[PendingUpdate],
    score: int,
) -> str:
    context = build_context(metrics)
    lines: List[str] = []
    lines.append("# Aetheris host report")
    lines.append("")
    lines.append(f"Scan time: {context['scan_time']}")
    lines.append("")
    lines.append("## Host")
    lines.append("")
    lines.append(f"- Hostname: `{context['hostname']}`")
    lines.append(f"- Platform: `{context['platform']}` (`{context['arch'] or 'n/a'}`)")
    lines.append(f"- Uptime: {context['uptime']}")
    lines.append(f"- CPU cores: {context['cores'] or 'n/a'}")
    lines.append(f"- Python: {context['python']}")
    lines.append("")

    lines.append("## Score")
    lines.append("")
    lines.append(f"**{score}/100** (grade {grade(score)})")
    lines.append("")

    lines.append("## Optimizations")
    lines.append("")
    if findings:
        lines.append("| Severity | Finding | Detail | Fix |")
        lines.append("| --- | --- | --- | --- |")
        for finding in findings:
            fix = f"`{finding.fix}`" if finding.fix else "n/a"
            lines.append(f"| {finding.severity} | {finding.title} | {finding.detail} | {fix} |")
    else:
        lines.append("No optimization opportunities detected.")
    lines.append("")

    lines.append("## Pending updates")
    lines.append("")
    if updates:
        lines.append("| Manager | Package | Current | Available |")
        lines.append("| --- | --- | --- | --- |")
        for update in updates:
            lines.append(
                f"| {update.manager} | {update.package} | {update.current} | {update.available} |"
            )
    else:
        lines.append("No pending package updates detected.")
    lines.append("")

    lines.append("---")
    lines.append("")
    lines.append("Generated by `aetheris-ops`. Run `aetheris-ops report` on the host to refresh.")
    return "\n".join(lines)


def render_json(
    metrics: Dict,
    findings: List[Finding],
    updates: List[PendingUpdate],
    score: int,
) -> dict:
    """Full JSON report."""
    return {
        "schemaVersion": 1,
        "label": "host score",
        "message": f"{score}/100",
        "color": _score_color(score),
        "report": {
            "scan_time": current_time(),
            "hostname": metrics.get("hostname"),
            "platform": metrics.get("platform"),
            "score": score,
            "grade": grade(score),
            "optimizations": [finding.to_dict() for finding in findings],
            "pending_updates": [update.to_dict() for update in updates],
        },
    }


def _score_color(score: int) -> str:
    if score >= 85:
        return "success"
    if score >= 70:
        return "yellow"
    if score >= 50:
        return "orange"
    return "critical"


def write_report(
    metrics: Dict,
    findings: List[Finding],
    updates: List[PendingUpdate],
    score: int,
    markdown_path: Optional[str] = None,
    json_path: Optional[str] = None,
) -> None:
    """Persist reports to disk when paths are provided."""
    if markdown_path:
        payload = render_markdown(metrics, findings, updates, score)
        with open(markdown_path, "w", encoding="utf-8") as handle:
            handle.write(payload)
    if json_path:
        payload = render_json(metrics, findings, updates, score)
        with open(json_path, "w", encoding="utf-8") as handle:
            json.dump(payload, handle, indent=2)
